FROM node:20-slim

RUN apt update && apt install -y \
  git gpg gnupg gpg-agent socat \
  ca-certificates \
  zsh \
  curl \
  wget \
  fonts-powerline \
  procps \
  chromium

# USER node - TODO: usar esse usuário por segurança

RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.2/zsh-in-docker.sh)" -- \
  -t https://github.com/denysdovhan/spaceship-prompt \
  -p git \
  -p ssh-agent \
  -p https://github.com/zdharma-continuum/fast-syntax-highlighting \
  -p https://github.com/zsh-users/zsh-autosuggestions \
  -p https://github.com/zsh-users/zsh-completions

ARG WORK_DIR=/davifsroberto_frontend
ENV PATH ${WORK_DIR}/node_modules/.bin:$PATH

RUN mkdir ${WORK_DIR}
WORKDIR ${WORK_DIR}

COPY package*.json /davifsroberto_frontend

RUN npm install -g @angular/cli@17
RUN npm install

COPY . /davifsroberto_frontend

RUN echo '[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh' >> ~/.zshrc && \
  echo 'HISTFILE=/davifsroberto_frontend/zsh/.zsh_history' >> ~/.zshrc

EXPOSE 4210

CMD [".docker/start.sh"]
